### ISSUE TITLE
Uploading message

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/art-director#2]
It's a little visually jarring how the "Uploading files" message pushes the editor down and then pushes it back up when it's done. 

Could we just replace it with a spinner that is an overlay like the drop files to upload message? I think it would look cleaner that way.

**Comment by jrtashjian** [comment]
Yeah, I meant to do something better here but forgot to add the task. Here's what it will look like in the next push:

![screenshot_2018-11-06 edit post sorta brilliant wordpress 1](https://user-images.githubusercontent.com/375788/48109208-7da52b80-e214-11e8-8606-a79fa672ce69.png)
