### ISSUE TITLE
Fix width and wrapping

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/art-director#3]
Can we make it so it never generates a vertical scrollbar?

In the customizer it seems to never have a vertical scrollbar. I tried to dig into the CSS but couldn't figure out what needed to be changed. 

Also they set the whitespace setting to pre-wrap which breaks urls into several lines which helps.
<img width="315" alt="screen shot 2018-11-06 at 7 43 53 pm" src="https://user-images.githubusercontent.com/158918/48105241-504c8380-e1fc-11e8-9eac-019af30a385f.png">

**Comment by jrtashjian** [comment]
It's actually a configuration item in the JavaScript of the CodeMirror component. Easy enough to toggle.
